FROM armv7/armhf-ubuntu:14.04.3
MAINTAINER kayrus

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y && apt-get install -yy -q wget \
    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
    && DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Generate the locale
RUN locale-gen en_US.UTF-8

# Add plex user
RUN useradd -r -d /var/lib/plex -s /sbin/nologin plex
VOLUME ["/var/lib/plex","/media"]
RUN install -d -o plex -g plex /opt/plex/Application
# Start container using plex user
USER plex

# Plex web interface default port
EXPOSE 32400/tcp
WORKDIR /opt/plex/Application

ENV PLEX_VERSION 1.2.7.2987-1bef33a
# Download QNAP ARMv7-X31+ archive and extract it (https://plex.tv/downloads) https://downloads.plex.tv/plex-media-server/${PLEX_VERSION}/plexmediaserver-ros6-binaries-annapurna_${PLEX_VERSION}_armel.deb
# https://downloads.plex.tv/codecs/ecd8c57-1099/linux-annapurnatrans-arm7/libaac_encoder.so
#RUN wget https://downloads.plex.tv/plex-media-server/${PLEX_VERSION}/plexmediaserver-ros6-binaries-annapurna_${PLEX_VERSION}_armel.deb -O /tmp/plex_media_server.deb
COPY plexmediaserver-ros6-binaries-annapurna_${PLEX_VERSION}_armel.deb /tmp/plex_media_server.deb
RUN dpkg-deb --fsys-tarfile /tmp/plex_media_server.deb | tar -xf - -C /opt/plex/Application --strip-components=4 ./apps/plexmediaserver-annapurna/Binaries

ADD start.sh /opt/plex/Application/start.sh

# Fix performance issues related to 6 channels processing
RUN sed -i 's/name="audio.channels" value="6"/name="audio.channels" value="2"/' /opt/plex/Application/Resources/Profiles/Web.xml

# This hack is a workaround for this issue http://forums.plex.tv/discussion/comment/1216192
RUN mv /opt/plex/Application/Plex\ Transcoder /opt/plex/Application/Plex\ Transcoder_
ADD magic.sh /opt/plex/Application/
RUN mv /opt/plex/Application/magic.sh /opt/plex/Application/Plex\ Transcoder

ENTRYPOINT /opt/plex/Application/start.sh
